version: '2'

services:
  php:
    build: ./php
    volumes:
      - ./src/my-app:/var/www

  nginx:
    image: nginx
    ports:
      - "8082:80"
    volumes:
      - ./src/my-app:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: mysql
